export const COUNTRIES = [
    {"codigo": "",  "nome": "-", "nomeFormal": ""},
    {"codigo": "004",  "nome": "Afeganistão", "nomeFormal": "República Islâmica do Afeganistão"},
    {"codigo": "008",  "nome": "Albânia", "nomeFormal": "República da Albânia"},
    {"codigo": "012",  "nome": "Algéria", "nomeFormal": 'República Democrática Popular da Algéria'},
    {"codigo": "016",  "nome": "Samoa Americana", "nomeFormal": "Território de Samoa Americana"},
    {"codigo": "020",  "nome": "Andorra", "nomeFormal": "Principado Andorra"},
    {"codigo": "024",  "nome": "Angola", "nomeFormal": "República de Angola"},
    {"codigo": "660",  "nome": "Anguilla", "nomeFormal": "Anguilla"},
    {"codigo": "010",  "nome": "Antártida", "nomeFormal": "Antártida"},
    {"codigo": "028",  "nome": "Antigua e Barbuda", "nomeFormal": "Antigua e Barbuda"},
    {"codigo": "032",  "nome": "Argentina", "nomeFormal": "República Argentina"},
    {"codigo": "051",  "nome": "Armênia", "nomeFormal": "República da Armênia"},
    {"codigo": "533",  "nome": "Aruba", "nomeFormal": "Aruba"},
    {"codigo": "036",  "nome": "Austrália", "nomeFormal": "Comunidade da Austrália"},
    {"codigo": "040",  "nome": "Áustria", "nomeFormal": "República da Áustria"},
    {"codigo": "031",  "nome": "Azerbaijão", "nomeFormal": "República do Azerbaijão"},
    {"codigo": "044",  "nome": "Bahamas", "nomeFormal": "Comunidade de Bahamas"},
    {"codigo": "048",  "nome": "Bahrein", "nomeFormal": "Reino do Bahrein"},
    {"codigo": "050",  "nome": "Bangladesh", "nomeFormal": "República Popular de Bangladesh"},
    {"codigo": "052",  "nome": "Barbados", "nomeFormal": "Barbados"},
    {"codigo": "112",  "nome": "Bielorrússia", "nomeFormal": "República da Bielorrússia"},
    {"codigo": "056",  "nome": "Bélgica", "nomeFormal": "Reino da Bélgica"},
    {"codigo": "084",  "nome": "Belize", "nomeFormal": "Belize"},
    {"codigo": "204",  "nome": "Benin", "nomeFormal": "República do Benin"},
    {"codigo": "060",  "nome": "Bermuda", "nomeFormal": "Bermuda"},
    {"codigo": "064",  "nome": "Butão", "nomeFormal": "Reino do Butão"},
    {"codigo": "068",  "nome": "Bolívia", "nomeFormal": "Estado Plurinacional da Bolívia"},
    {"codigo": "070",  "nome": "Bósnia e Herzegovina", "nomeFormal": "Bósnia e Herzegovina"},
    {"codigo": "072",  "nome": "Botswana", "nomeFormal": "República da Botswana"},
    {"codigo": "074",  "nome": "Ilha Bouvet", "nomeFormal": "Ilha Bouvet"},
    {"codigo": "076",  "nome": "Brasil", "nomeFormal": "República Federativa do Brasil"},
    {"codigo": "086",  "nome": "Território Britânico do Oceano Índico", "nomeFormal": "Território Britânico do Oceano Índico"},
    {"codigo": "096",  "nome": "Brunei", "nomeFormal": "Estado do Brunei Darussalam"},
    {"codigo": "100",  "nome": "Bulgária", "nomeFormal": "República da Bulgária"},
    {"codigo": "854",  "nome": "Burkina Faso", "nomeFormal": "Burkina Faso"},
    {"codigo": "108",  "nome": "Burundi", "nomeFormal": "República do Burundi"},
    {"codigo": "116",  "nome": "Camboja", "nomeFormal": "Reino do Camboja"},
    {"codigo": "120",  "nome": "Camarões", "nomeFormal": "República de Camarões"},
    {"codigo": "124",  "nome": "Canadá", "nomeFormal": "Canadá"},
    {"codigo": "132",  "nome": "Cabo Verde", "nomeFormal": "República do Cabo Verde"},
    {"codigo": "136",  "nome": "Ilhas Cayman", "nomeFormal": "Ilhas Cayman"},
    {"codigo": "140",  "nome": "República Centro-Africana", "nomeFormal": "República Centro-Africana"},
    {"codigo": "148",  "nome": "Chade", "nomeFormal": "República do Chade"},
    {"codigo": "152",  "nome": "Chile", "nomeFormal": "República do Chile"},
    {"codigo": "156",  "nome": "China", "nomeFormal": "República Popular da China"},
    {"codigo": "162",  "nome": "Ilha Christmas", "nomeFormal": "Território da Ilha Christmas"},
    {"codigo": "166",  "nome": "Ilhas Cocos (Keeling)", "nomeFormal": "Território das Ilhas Cocos (Keeling)"},
    {"codigo": "170",  "nome": "Colômbia", "nomeFormal": "República da Colômbia"},
    {"codigo": "174",  "nome": "Comores", "nomeFormal": "União das Comores"},
    {"codigo": "178",  "nome": "Congo", "nomeFormal": "República do Congo"},
    {"codigo": "180",  "nome": "Congo (DR)", "nomeFormal": "República Democrática do Congo"},
    {"codigo": "184",  "nome": "Ilhas Cook", "nomeFormal": "Ilhas Cook"},
    {"codigo": "188",  "nome": "Costa Rica", "nomeFormal": "República da Costa Rica"},
    {"codigo": "384",  "nome": "Costa do Marfim", "nomeFormal": "República da Costa do Marfim"},
    {"codigo": "191",  "nome": "Croácia", "nomeFormal": "República da Croácia"},
    {"codigo": "192",  "nome": "Cuba", "nomeFormal": "República de Cuba"},
    {"codigo": "196",  "nome": "Chipre", "nomeFormal": "República do Chipre"},
    {"codigo": "203",  "nome": "República Tcheca", "nomeFormal": "República Tcheca"},
    {"codigo": "208",  "nome": "Dinamarca", "nomeFormal": "Reino da Dinamarca"},
    {"codigo": "262",  "nome": "Djibuti", "nomeFormal": "República do Djibuti"},
    {"codigo": "212",  "nome": "Dominica", "nomeFormal": "Comunidade da Dominica"},
    {"codigo": "214",  "nome": "República Dominicana", "nomeFormal": "República Dominicana"},
    {"codigo": "218",  "nome": "Equador", "nomeFormal": "República do Equador"},
    {"codigo": "818",  "nome": "Egito", "nomeFormal": "República Árabe do Egito"},
    {"codigo": "222",  "nome": "El Salvador", "nomeFormal": "República El Salvador"},
    {"codigo": "226",  "nome": "Guiné Equatorial", "nomeFormal": "República do Guiné Equatorial"},
    {"codigo": "232",  "nome": "Eritreia", "nomeFormal": "Estado da Eritreia"},
    {"codigo": "233",  "nome": "Estônia", "nomeFormal": "República da Estônia"},
    {"codigo": "231",  "nome": "Etiópia", "nomeFormal": "República Democrática Federal da Etiópia"},
    {"codigo": "238",  "nome": "Ilhas Malvinas", "nomeFormal": "Ilhas Malvinas"},
    {"codigo": "234",  "nome": "Ilhas Faroe", "nomeFormal": "Ilhas Faroe"},
    {"codigo": "242",  "nome": "Fiji", "nomeFormal": "República do Fiji"},
    {"codigo": "246",  "nome": "Finlândia", "nomeFormal": "República da Finlândia"},
    {"codigo": "250",  "nome": "França", "nomeFormal": "República Francesa"},
    {"codigo": "254",  "nome": "Guiana Francesa", "nomeFormal": "Guiana Francesa"},
    {"codigo": "258",  "nome": "Polinésia Francesa", "nomeFormal": "Polinésia Francesa"},
    {"codigo": "260",  "nome": "Terras Austrais e Antárticas Francesas", "nomeFormal": "Território das Terras Austrais e Antárticas Francesas"},
    {"codigo": "266",  "nome": "Gabão", "nomeFormal": "República Gabonesa"},
    {"codigo": "270",  "nome": "Gâmbia", "nomeFormal": "República da Gâmbia"},
    {"codigo": "268",  "nome": "Geórgia", "nomeFormal": "Geórgia"},
    {"codigo": "276",  "nome": "Alemanha", "nomeFormal": "República Federal da Alemanha"},
    {"codigo": "288",  "nome": "Gana", "nomeFormal": "Repúblia de Gana"},
    {"codigo": "292",  "nome": "Gibraltar", "nomeFormal": "Gibraltar"},
    {"codigo": "300",  "nome": "Grécia", "nomeFormal": "República Helênica"},
    {"codigo": "304",  "nome": "Groelândia", "nomeFormal": "Groelândia"},
    {"codigo": "308",  "nome": "Granada", "nomeFormal": "Granada"},
    {"codigo": "312",  "nome": "Guadalupe", "nomeFormal": "Guadalupe"},
    {"codigo": "316",  "nome": "Guão", "nomeFormal": "Território do Guão"},
    {"codigo": "320",  "nome": "Guatemala", "nomeFormal": "República da Guatemala"},
    {"codigo": "324",  "nome": "Guiné", "nomeFormal": "República do Guiné"},
    {"codigo": "624",  "nome": "Guiné-Bissau", "nomeFormal": "República da Guiné-Bissau"},
    {"codigo": "328",  "nome": "Guiana", "nomeFormal": "República Cooperativa da Guiana"},
    {"codigo": "332",  "nome": "Haiti", "nomeFormal": "República do Haiti"},
    {"codigo": "334",  "nome": "Ilhas Heard e McDonald", "nomeFormal": "Território das Ilhas Heard e McDonald"},
    {"codigo": "336",  "nome": "Vaticano", "nomeFormal": "Estado da Cidade do Vaticano"},
    {"codigo": "340",  "nome": "Honduras", "nomeFormal": "República de Honduras"},
    {"codigo": "344",  "nome": "Hong Kong", "nomeFormal": "Região Administrativa Especial de Hong Kong da República Popular da China"},
    {"codigo": "348",  "nome": "Hungria", "nomeFormal": "Hungria"},
    {"codigo": "352",  "nome": "Islândia", "nomeFormal": "Islândia"},
    {"codigo": "356",  "nome": "Índia", "nomeFormal": "República da Índia"},
    {"codigo": "360",  "nome": "Indonésia", "nomeFormal": "República da Indonésia"},
    {"codigo": "364",  "nome": "Iran", "nomeFormal": "República Islâmica do Iran"},
    {"codigo": "368",  "nome": "Iraque", "nomeFormal": "República do Iraque"},
    {"codigo": "372",  "nome": "Irlanda", "nomeFormal": "Irlanda"},
    {"codigo": "376",  "nome": "Israel", "nomeFormal": "Estado de Israel"},
    {"codigo": "380",  "nome": "Italia", "nomeFormal": "República Italiana"},
    {"codigo": "388",  "nome": "Jamaica", "nomeFormal": "Jamaica"},
    {"codigo": "392",  "nome": "Japão", "nomeFormal": "Japão"},
    {"codigo": "400",  "nome": "Jornânia", "nomeFormal": "Reino Hachemita da Jordânia"},
    {"codigo": "398",  "nome": "Cazaquistão", "nomeFormal": "República do Cazaquistão"},
    {"codigo": "404",  "nome": "Quênia", "nomeFormal": "República do Quênia"},
    {"codigo": "296",  "nome": "Kiribati", "nomeFormal": "República do Kiribati"},
    {"codigo": "408",  "nome": "Coreia do Norte", "nomeFormal": "República Democrática Popular da Coreia"},
    {"codigo": "410",  "nome": "Coreia do Sul", "nomeFormal": "República da Coreia"},
    {"codigo": "414",  "nome": "Kuwait", "nomeFormal": "Estado do Kuwait"},
    {"codigo": "417",  "nome": "Quirguistão", "nomeFormal": "República Quirguiz"},
    {"codigo": "418",  "nome": "Laos", "nomeFormal": "República Democrática Popular Lau"},
    {"codigo": "428",  "nome": "Letônia", "nomeFormal": "República da Letônia"},
    {"codigo": "422",  "nome": "Líbano", "nomeFormal": "República Libanesa"},
    {"codigo": "426",  "nome": "Lesoto", "nomeFormal": "Reino do Lesoto"},
    {"codigo": "430",  "nome": "Libéria", "nomeFormal": "República da Libéria"},
    {"codigo": "434",  "nome": "Líbia", "nomeFormal": "Líbia"},
    {"codigo": "438",  "nome": "Liechtenstein", "nomeFormal": "Principado de Liechtenstein"},
    {"codigo": "440",  "nome": "Lituânia", "nomeFormal": "República da Lituânia"},
    {"codigo": "442",  "nome": "Luxemburgo", "nomeFormal": "Grão-Ducado do Luxemburgo"},
    {"codigo": "446",  "nome": "Macao", "nomeFormal": "Macao"},
    {"codigo": "807",  "nome": "Macedônia", "nomeFormal": "República da Macedônia"},
    {"codigo": "450",  "nome": "Madagascar", "nomeFormal": "República de Madagascar"},
    {"codigo": "454",  "nome": "Malawi", "nomeFormal": "República de Malawi"},
    {"codigo": "458",  "nome": "Malásia", "nomeFormal": "Malásia"},
    {"codigo": "462",  "nome": "Maldivas", "nomeFormal": "Reública de Maldivas"},
    {"codigo": "466",  "nome": "Mali", "nomeFormal": "República do Mali"},
    {"codigo": "470",  "nome": "Malta", "nomeFormal": "República de Malta"},
    {"codigo": "584",  "nome": "Ilhas Marshall", "nomeFormal": "República das Ilhas Marshall"},
    {"codigo": "474",  "nome": "Martinica", "nomeFormal": "Martinica"},
    {"codigo": "478",  "nome": "Mauritânia", "nomeFormal": "República Islâmica da Mauritânia"},
    {"codigo": "480",  "nome": "Maurício", "nomeFormal": "República de Maurício"},
    {"codigo": "175",  "nome": "Mayotte", "nomeFormal": "Departamento de Mayotte"},
    {"codigo": "484",  "nome": "México", "nomeFormal": "Estados Unidos Mexicanos"},
    {"codigo": "583",  "nome": "Micronésia", "nomeFormal": "Estados Federados da Micronesia"},
    {"codigo": "498",  "nome": "Moldova", "nomeFormal": "República de Moldova"},
    {"codigo": "492",  "nome": "Mônaco", "nomeFormal": "Principado de Mônaco"},
    {"codigo": "496",  "nome": "Mongólia", "nomeFormal": "Mongólia"},
    {"codigo": "500",  "nome": "Montserrat", "nomeFormal": "Montserrat"},
    {"codigo": "504",  "nome": "Marrocos", "nomeFormal": "Reino de Marrocos"},
    {"codigo": "508",  "nome": "Moçambique", "nomeFormal": "República de Moçambique"},
    {"codigo": "104",  "nome": "Birmânia", "nomeFormal": "República da União de Myanmar"},
    {"codigo": "516",  "nome": "Namíbia", "nomeFormal": "República da Namíbia"},
    {"codigo": "520",  "nome": "Nauru", "nomeFormal": "República de Nauru"},
    {"codigo": "524",  "nome": "Nepal", "nomeFormal": "República Democrática Federativa do Nepal"},
    {"codigo": "528",  "nome": "Holanda", "nomeFormal": "Holanda"},
    {"codigo": "530",  "nome": "Antilhas Holandesas", "nomeFormal": "Antilhas Holandesas"},
    {"codigo": "540",  "nome": "Nova Caledônia", "nomeFormal": "Nova Caledônia"},
    {"codigo": "554",  "nome": "Nova Zelândia", "nomeFormal": "Nova Zelândia"},
    {"codigo": "558",  "nome": "Nicarágua", "nomeFormal": "República da Nicarágua"},
    {"codigo": "562",  "nome": "Niger", "nomeFormal": "República do Niger"},
    {"codigo": "566",  "nome": "Nigéria", "nomeFormal": "República Federativa da Nigéria"},
    {"codigo": "570",  "nome": "Niue", "nomeFormal": "Niue"},
    {"codigo": "574",  "nome": "Ilha Norfolk", "nomeFormal": "Território da Ilha Norfolk"},
    {"codigo": "580",  "nome": "Ilhas Marianas do Norte", "nomeFormal": "Comunidade das Ilhas Marianas do Norte"},
    {"codigo": "578",  "nome": "Noruega", "nomeFormal": "Reino da Noruega"},
    {"codigo": "512",  "nome": "Omã", "nomeFormal": "Sultanato de Omã"},
    {"codigo": "586",  "nome": "Paquistão", "nomeFormal": "República Islâmica do Paquistão"},
    {"codigo": "585",  "nome": "Palau", "nomeFormal": "República de Palau"},
    {"codigo": "275",  "nome": "Palestina", "nomeFormal": "Estado da Palestina"},
    {"codigo": "591",  "nome": "Panamá", "nomeFormal": "República do Panamá"},
    {"codigo": "598",  "nome": "Papua-Nova Guiné", "nomeFormal": "Estado Independente da Papua-Nova Guiné"},
    {"codigo": "600",  "nome": "Paraguai", "nomeFormal": "República do Paraguai"},
    {"codigo": "604",  "nome": "Peru", "nomeFormal": "República do Peru"},
    {"codigo": "608",  "nome": "Filipinas", "nomeFormal": "República das Filipinas"},
    {"codigo": "612",  "nome": "Ilhas Picárnia", "nomeFormal": "Ilhas Picárnia"},
    {"codigo": "616",  "nome": "Polônia", "nomeFormal": "República da Polônia"},
    {"codigo": "620",  "nome": "Portugal", "nomeFormal": "República Portuguesa"},
    {"codigo": "630",  "nome": "Porto Rico", "nomeFormal": "Comunidade do Porto Rico"},
    {"codigo": "634",  "nome": "Catar", "nomeFormal": "Estado do Catar"},
    {"codigo": "638",  "nome": "Reunião", "nomeFormal": "Polônia"},
    {"codigo": "642",  "nome": "Romênia", "nomeFormal": "Romênia"},
    {"codigo": "643",  "nome": "Rússia", "nomeFormal": "Federação Russa"},
    {"codigo": "646",  "nome": "Ruanda", "nomeFormal": "República da Ruanda"},
    {"codigo": "654",  "nome": "Santa Helena", "nomeFormal": "Saint Helena"},
    {"codigo": "659",  "nome": "São Cristóvão", "nomeFormal": "São Cristóvão"},
    {"codigo": "662",  "nome": "Santa Lúcia", "nomeFormal": "Santa Lúcia"},
    {"codigo": "666",  "nome": "São Pedro e Miquelon", "nomeFormal": "Coletividade Territorial de São Pedro e Miquelon"},
    {"codigo": "670",  "nome": "São Vicente e Granadinas", "nomeFormal": "São Vicente e Granadinas"},
    {"codigo": "882",  "nome": "Samoa", "nomeFormal": "Estado Independente de Samoa"},
    {"codigo": "674",  "nome": "São Marino", "nomeFormal": "República de São Marino"},
    {"codigo": "678",  "nome": "Sao Tomé e Príncipe", "nomeFormal": "República Democrática de Sao Tomé e Príncipe"},
    {"codigo": "682",  "nome": "Arábia Saudita", "nomeFormal": "Reino da Arábia Saudita"},
    {"codigo": "686",  "nome": "Senegal", "nomeFormal": "República do Senegal"},
    {"codigo": "688",  "nome": "Sérvia e Montenegro", "nomeFormal": "União Estatal de Sérvia e Montenegro"},
    {"codigo": "690",  "nome": "Seicheles", "nomeFormal": "República das Seicheles"},
    {"codigo": "694",  "nome": "República da Serra Leoa", "nomeFormal": "República da Serra Leoa"},
    {"codigo": "702",  "nome": "Singapura", "nomeFormal": "República da Singapura"},
    {"codigo": "703",  "nome": "Eslováquia", "nomeFormal": "República Eslovaca"},
    {"codigo": "705",  "nome": "Eslovênia", "nomeFormal": "República da Eslovênia"},
    {"codigo": "090",  "nome": "Ilhas Salomão", "nomeFormal": "Ilhas Salomão"},
    {"codigo": "706",  "nome": "Somália", "nomeFormal": "República da Somália"},
    {"codigo": "710",  "nome": "África do Sul", "nomeFormal": "República da África do Sul"},
    {"codigo": "239",  "nome": "Ilhas Geórgia do Sul e Sandwich do Sul", "nomeFormal": "Ilhas Geórgia do Sul e Sandwich do Sul"},
    {"codigo": "724",  "nome": "Espanha", "nomeFormal": "Reino da Espanha"},
    {"codigo": "144",  "nome": "Sri Lanka", "nomeFormal": "República Democrática Socialista do Sri Lanka"},
    {"codigo": "736",  "nome": "Sudão", "nomeFormal": "República do Sudão"},
    {"codigo": "740",  "nome": "Suriname", "nomeFormal": "República do Suriname"},
    {"codigo": "744",  "nome": "Esvalbarde", "nomeFormal": "Esvalbarde"},
    {"codigo": "748",  "nome": "Suazilândia", "nomeFormal": "Reino da Suazilândia"},
    {"codigo": "752",  "nome": "Suécia", "nomeFormal": "Reino da Suécia"},
    {"codigo": "756",  "nome": "Suiça", "nomeFormal": "Confederação Suiça"},
    {"codigo": "760",  "nome": "Síria", "nomeFormal": "República Árabe Síria"},
    {"codigo": "158",  "nome": "Taiwan", "nomeFormal": "Taiwan"},
    {"codigo": "762",  "nome": "Tajiquistão", "nomeFormal": "República do Tajiquistão"},
    {"codigo": "834",  "nome": "Tanzânia", "nomeFormal": "República Unida da Tanzânia"},
    {"codigo": "764",  "nome": "Tailândia", "nomeFormal": "Reino da Tailândia"},
    {"codigo": "626",  "nome": "Timor-Leste", "nomeFormal": "República Democrática de Timor-Leste"},
    {"codigo": "768",  "nome": "Togo", "nomeFormal": "República Togolesa"},
    {"codigo": "772",  "nome": "Toquelau", "nomeFormal": "Toquelau"},
    {"codigo": "776",  "nome": "Tonga", "nomeFormal": "Reino de Tonga"},
    {"codigo": "780",  "nome": "Trinidad e Tobago", "nomeFormal": "República da Trinidad e Tobago"},
    {"codigo": "788",  "nome": "Tunísia", "nomeFormal": "República da Tunísia"},
    {"codigo": "792",  "nome": "Turquia", "nomeFormal": "República da Turquia"},
    {"codigo": "795",  "nome": "Turcomenistão", "nomeFormal": "Turcomenistão"},
    {"codigo": "796",  "nome": "Ilhas Turks e Caicos", "nomeFormal": "Ilhas Turks e Caicos"},
    {"codigo": "798",  "nome": "Tuvalu", "nomeFormal": "Tuvalu"},
    {"codigo": "800",  "nome": "Uganda", "nomeFormal": "República de Uganda"},
    {"codigo": "804",  "nome": "Ucrânia", "nomeFormal": "Ucrânia"},
    {"codigo": "784",  "nome": "Emirados Árabes", "nomeFormal": "Emirados Árabes Unidos"},
    {"codigo": "826",  "nome": "Reino Unido", "nomeFormal": "Reino Unido da Grã-Bretanha e Irlanda do Norte"},
    {"codigo": "840",  "nome": "Estados Unidos", "nomeFormal": "Estados Unidos da América"},
    {"codigo": "581",  "nome": "Ilhas Menores Distantes dos Estados Unidos", "nomeFormal": "Ilhas Menores Distantes dos Estados Unidos"},
    {"codigo": "858",  "nome": "Uruguai", "nomeFormal": "República Oriental do Uruguai"},
    {"codigo": "860",  "nome": "Uzbequistão", "nomeFormal": "República do Uzbequistão"},
    {"codigo": "548",  "nome": "Vanuatu", "nomeFormal": "República de Vanuatu"},
    {"codigo": "862",  "nome": "Venezuela", "nomeFormal": "República Bolivariana da Venezuela"},
    {"codigo": "704",  "nome": "Vietnam", "nomeFormal": "República Socialista do Vietnam"},
    {"codigo": "092",  "nome": "Ilhas Virgens Inglesas", "nomeFormal": "Ilhas Virgens"},
    {"codigo": "850",  "nome": "Ilhas Virgens (USA)", "nomeFormal": "Ilhas Virgens dos Estados Unidos"},
    {"codigo": "876",  "nome": "Wallis e Futuna", "nomeFormal": "Wallis e Futuna"},
    {"codigo": "732",  "nome": "Saara Ocidental", "nomeFormal": "Saara Ocidental"},
    {"codigo": "887",  "nome": "Iêmen", "nomeFormal": "República do Iêmen"},
    {"codigo": "894",  "nome": "Zâmbia", "nomeFormal": "República do Zâmbia"},
    {"codigo": "716",  "nome": "Zimbábue", "nomeFormal": "República do Zimbábue"}
];
